from fastapi import APIRouter, Response, Depends
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
from backend.database import get_db
from backend.crud import get_scheme_by_id
from typing import Optional

router = APIRouter()

@router.get("/download-guide/{scheme_id}")
async def download_guide(scheme_id: str, name: Optional[str] = "Applicant", db: Session = Depends(get_db)):
    scheme_obj = get_scheme_by_id(db, scheme_id)
    if not scheme_obj:
        return {"error": "Scheme not found"}
    
    scheme = scheme_obj.__dict__

    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    p.setFont("Helvetica-Bold", 24)
    p.drawString(100, height - 80, "Yojana.AI Application Guide")
    
    p.setFont("Helvetica", 12)
    p.drawString(100, height - 105, f"Personalized for: {name}")
    p.line(100, height - 115, 500, height - 115)

    # Scheme Details
    p.setFont("Helvetica-Bold", 18)
    p.drawString(100, height - 150, f"Scheme: {scheme['name']}")
    
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, height - 180, "Benefits:")
    p.setFont("Helvetica", 12)
    p.drawString(100, height - 200, scheme["benefits"])

    # Document Checklist
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, height - 240, "Required Documents Checklist:")
    
    y = height - 265
    p.setFont("Helvetica", 12)
    for doc in scheme["required_documents"]:
        p.drawString(120, y, f"[ ] {doc}")
        y -= 20

    # Next Steps
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, y - 20, "Next Steps:")
    p.setFont("Helvetica", 12)
    p.drawString(100, y - 40, f"1. Collect all documents listed above.")
    p.drawString(100, y - 60, f"2. Visit the official portal: {scheme['apply_url']}")
    p.drawString(100, y - 80, f"3. Apply before the deadline: {scheme['deadline']}")

    # Footer
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(100, 50, "Generated by Yojana.AI - Empowering citizens through technology.")

    p.showPage()
    p.save()

    buffer.seek(0)
    return Response(
        content=buffer.getvalue(), 
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={scheme_id}_guide.pdf"}
    )
