from backend.database import SessionLocal, engine, Base
from backend.db_models import Scheme
import json

Base.metadata.create_all(bind=engine)

SCHEMES_LIST = [
    {
        "id": "pm_kisan",
        "name": "PM Kisan Samman Nidhi",
        "icon": "🚜",
        "description": "Financial assistance to small and marginal farmers across the country.",
        "benefits": "₹6,000 per year in three equal installments.",
        "max_income": 300000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Farmer"],
        "eligible_categories": ["All"],
        "land_owned_required": True,
        "required_documents": ["Aadhaar Card", "Bank Passbook", "Land Records"],
        "deadline": "Rolling",
        "apply_url": "https://pmkisan.gov.in/",
        "category": "Agriculture",
        "popularity": 95,
        "guidance_steps": [
            "Visit the official PM-Kisan portal.",
            "Click on 'New Farmer Registration' and enter your Aadhaar number.",
            "Fill in the required land details and upload your passbook.",
            "Submit and note down your reference number for tracking."
        ]
    },
    {
        "id": "swami_vivekananda_scholarship",
        "name": "Swami Vivekananda Merit-cum-Means Scholarship",
        "icon": "🎓",
        "description": "Scholarship for meritorious students from economically weaker sections in West Bengal.",
        "benefits": "Up to ₹60,000 per year depending on course.",
        "max_income": 250000,
        "eligible_states": ["West Bengal"],
        "eligible_occupations": ["Student"],
        "eligible_categories": ["All"],
        "min_age": 15,
        "required_documents": ["Previous Marksheet", "Income Certificate", "Income Affidavit", "Aadhaar Card"],
        "deadline": "31st Dec",
        "apply_url": "https://svmcm.wbhed.gov.in/",
        "category": "Education",
        "popularity": 88,
        "guidance_steps": [
            "Register on the SVMCM portal with your academic details.",
            "Login and fill the detailed application form.",
            "Upload scanned income certificates and marksheets.",
            "Submit and wait for institutional verification."
        ]
    },
    {
        "id": "mudra_loan",
        "name": "Pradhan Mantri Mudra Yojana (PMMY)",
        "icon": "💼",
        "description": "Loans up to ₹10 Lakhs for non-corporate, non-farm small/micro enterprises.",
        "benefits": "Collateral-free loans for starting or expanding businesses.",
        "max_income": 1000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Business Owner", "Self-Employed", "Entrepreneur"],
        "eligible_categories": ["All"],
        "required_documents": ["Identity Proof", "Address Proof", "Business Project Report", "Bank Statement"],
        "deadline": "Monthly",
        "apply_url": "https://www.mudra.org.in/",
        "category": "Finance",
        "popularity": 92,
        "guidance_steps": [
            "Identify the category (Shishu, Kishore, Tarun) based on loan amount.",
            "Download the Mudra loan application form from the website.",
            "Approach your nearest bank branch with the project report.",
            "Submit documents and complete the KYC process at the bank."
        ]
    },
    {
        "id": "kanyashree",
        "name": "Kanyashree Prakalpa",
        "icon": "👧",
        "description": "Incentivizing schooling and delaying marriage of girl children in West Bengal.",
        "benefits": "Annual scholarship and a one-time grant of ₹25,000.",
        "max_income": 120000,
        "eligible_states": ["West Bengal"],
        "eligible_occupations": ["Student"],
        "eligible_categories": ["All"],
        "gender": "Female",
        "min_age": 13,
        "max_age": 19,
        "required_documents": ["Birth Certificate", "Unmarried Declaration", "Aadhaar Card", "Bank Passbook"],
        "deadline": "Dec 31",
        "apply_url": "https://www.wbkanyashree.gov.in/",
        "category": "Social Welfare",
        "popularity": 85
    },
    {
        "id": "ayushman_bharat",
        "name": "Ayushman Bharat (PM-JAY)",
        "icon": "🏥",
        "description": "World's largest health insurance scheme fully financed by the government.",
        "benefits": "Health cover of ₹5 Lakh per family per year for secondary and tertiary care hospitalization.",
        "max_income": 600000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "required_documents": ["Aadhaar", "Ration Card", "Identity Proof"],
        "deadline": "Open",
        "apply_url": "https://pib.gov.in/PressReleasePage.aspx?PRID=1951508",
        "category": "Health",
        "popularity": 98
    },
    {
        "id": "pm_awas_yojana",
        "name": "PM Awas Yojana (PMAY)",
        "icon": "🏠",
        "description": "Housing for all by providing interest subsidies on home loans.",
        "benefits": "Subsidy up to ₹2.67 Lakhs on home loan interest.",
        "max_income": 1800000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "required_documents": ["Aadhaar", "Income Proof", "Affidavit of No Pucca House"],
        "deadline": "Dec 2026",
        "apply_url": "https://pmaymis.gov.in/",
        "category": "Housing",
        "popularity": 96,
        "guidance_steps": [
            "Check the eligible category (EWS, LIG, MIG).",
            "Apply online or through a registered bank/HFC.",
            "Submit the declaration bahwa you do not own a pucca house.",
            "Once approved, credit link subsidy will be added to your loan account."
        ]
    },
    {
        "id": "pm_ujjwala",
        "name": "PM Ujjwala Yojana",
        "icon": "🔥",
        "description": "Providing clean cooking fuel to BPL households.",
        "benefits": "Free LPG connection and first refill for eligible women.",
        "max_income": 200000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["SC", "ST", "OBC", "General (BPL)"],
        "gender": "Female",
        "required_documents": ["Ration Card", "BPL Certificate", "Aadhaar Card"],
        "deadline": "Ongoing",
        "apply_url": "https://www.pmuy.gov.in/",
        "category": "Social Welfare",
        "popularity": 94
    },
    {
        "id": "mgnrega",
        "name": "MGNREGA Employment",
        "icon": "⛏️",
        "description": "Legal guarantee for at least 100 days of wage employment in a financial year.",
        "benefits": "Guaranteed minimum wage and unemployment allowance if work not provided.",
        "max_income": 5000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Artisan", "Unemployed", "Farmer", "Manual Labor"],
        "eligible_categories": ["All"],
        "required_documents": ["Job Card", "Aadhaar Card"],
        "deadline": "Rolling",
        "apply_url": "https://nrega.nic.in/",
        "category": "Employment",
        "popularity": 97
    },
    {
        "id": "pm_shram_yogi",
        "name": "PM Shram Yogi Maandhan (PM-SYM)",
        "icon": "👴",
        "description": "Voluntary and contributory pension scheme for unorganized workers.",
        "benefits": "Minimum assured pension of ₹3,000 per month after age 60.",
        "max_income": 180000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Artisan", "Self-Employed", "Manual Labor", "Daily Wager"],
        "eligible_categories": ["All"],
        "min_age": 18,
        "max_age": 40,
        "required_documents": ["Savings Bank Account", "Aadhaar Card"],
        "deadline": "Ongoing",
        "apply_url": "https://maandhan.in/",
        "category": "Social Welfare",
        "popularity": 82
    },
    {
        "id": "nsap_pension",
        "name": "National Social Assistance Programme",
        "icon": "👵",
        "description": "Support to elderly, widows and disabled persons from BPL households.",
        "benefits": "Monthly pension ranging from ₹200 to ₹500 (plus state contributions).",
        "max_income": 100000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["General (BPL)"],
        "min_age": 60,
        "required_documents": ["BPL Card", "Age Proof", "Disability Certificate (if applicable)"],
        "deadline": "Ongoing",
        "apply_url": "https://nsap.nic.in/",
        "category": "Social Welfare",
        "popularity": 80
    },
    {
        "id": "pm_matru_vandana",
        "name": "PM Matru Vandana Yojana",
        "icon": "🤰",
        "description": "Maternity benefit program for pregnant and lactating mothers.",
        "benefits": "Cash incentive of ₹5,000 in three installments.",
        "max_income": 800000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "gender": "Female",
        "required_documents": ["Mother-Child Protection Card", "Bank Account Details"],
        "deadline": "Ongoing",
        "apply_url": "https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana",
        "category": "Health",
        "popularity": 86
    },
    {
        "id": "stand_up_india",
        "name": "Stand Up India Scheme",
        "icon": "📈",
        "description": "Bank loans between ₹10 lakh and ₹1 Crore to SC/ST and Women entrepreneurs.",
        "benefits": "Accessible financing for setting up greenfield enterprises.",
        "max_income": 5000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Entrepreneur"],
        "eligible_categories": ["SC", "ST", "All (if Female)"],
        "required_documents": ["Business Plan", "Caste Certificate", "Bank Statements"],
        "deadline": "Open",
        "apply_url": "https://www.standupmitra.in/",
        "category": "Finance",
        "popularity": 78
    },
    {
        "id": "pm_vishwakarma",
        "name": "PM Vishwakarma Scheme",
        "icon": "⚒️",
        "description": "Support for traditional artisans and craftspeople.",
        "benefits": "Skill training, tool kit incentive, and credit support.",
        "max_income": 600000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Artisan", "Carpenter", "Blacksmith", "Potter"],
        "eligible_categories": ["All"],
        "required_documents": ["Aadhaar", "Bank Passbook", "Caste Certificate"],
        "deadline": "Open",
        "apply_url": "https://pmvishwakarma.gov.in/",
        "category": "Skill Development",
        "popularity": 89
    },
    {
        "id": "sukanya_samriddhi",
        "name": "Sukanya Samriddhi Yojana",
        "icon": "💰",
        "description": "Savings scheme for the girl child education/marriage.",
        "benefits": "High interest rate and tax benefits.",
        "max_income": 5000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "gender": "Female",
        "max_age": 10,
        "required_documents": ["Birth Certificate", "Aadhaar Card of Parent"],
        "deadline": "Ongoing",
        "apply_url": "https://www.indiapost.gov.in/",
        "category": "Finance",
        "popularity": 91
    },
    {
        "id": "pm_poshan",
        "name": "PM POSHAN (Mid Day Meal)",
        "icon": "🍲",
        "description": "Ensuring nutrition for primary students.",
        "benefits": "Free warm nutritious meals in government schools.",
        "max_income": 9999999,
        "eligible_states": ["All"],
        "eligible_occupations": ["Student"],
        "eligible_categories": ["All"],
        "min_age": 5,
        "max_age": 14,
        "required_documents": ["School ID", "Ration Card"],
        "deadline": "Rolling",
        "apply_url": "https://pmposhan.education.gov.in/",
        "category": "Social Welfare",
        "popularity": 93
    },
    {
        "id": "startup_india_learning",
        "name": "Startup India Learning Program",
        "icon": "💡",
        "description": "Free online entrepreneurship program.",
        "benefits": "Certification and mentorship.",
        "max_income": 99999999,
        "eligible_states": ["All"],
        "eligible_occupations": ["Entrepreneur", "Student", "Unemployed"],
        "eligible_categories": ["All"],
        "required_documents": ["Email ID"],
        "deadline": "Always Open",
        "apply_url": "https://www.startupindia.gov.in/content/sih/en/learning-and-development_v2.html",
        "category": "Education",
        "popularity": 75
    },
    {
        "id": "atal_pension",
        "name": "Atal Pension Yojana (APY)",
        "icon": "👴",
        "description": "Pension scheme for citizens in the unorganized sector.",
        "benefits": "Fixed pension after age 60.",
        "max_income": 800000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "min_age": 18,
        "max_age": 40,
        "required_documents": ["Savings Bank Account", "Aadhaar Card"],
        "deadline": "Ongoing",
        "apply_url": "https://npscra.nsdl.co.in/scheme-details.php",
        "category": "Social Welfare",
        "popularity": 81
    },
    # --- New 14 Schemes ---
    {
        "id": "pm_svanidhi",
        "name": "PM SVANidhi (Street Vendor Loan)",
        "icon": "🏪",
        "description": "Micro-credit facility for street vendors to restart their livelihoods.",
        "benefits": "Working capital loan up to ₹10,000, ₹20,000, and ₹50,000 with interest subsidy.",
        "max_income": 300000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Street Vendor", "Small Trader"],
        "eligible_categories": ["All"],
        "required_documents": ["Aadhaar Card", "Voter ID", "Certificate of Vending"],
        "deadline": "Ongoing",
        "apply_url": "https://pmsvanidhi.mohua.gov.in/",
        "category": "Finance",
        "popularity": 84,
        "guidance_steps": [
            "Keep your mobile-linked Aadhaar ready.",
            "Apply via the PM SVANidhi portal or mobile app.",
            "Choose your preferred lender (Bank/NBFC).",
            "Submit the vending certificate issued by local bodies."
        ]
    },
    {
        "id": "lakhpati_didi",
        "name": "Lakhpati Didi Scheme",
        "icon": "👩‍🌾",
        "description": "Empowering women in Self-Help Groups (SHGs) to earn annual income of ₹1 Lakh or more.",
        "benefits": "Skill development training in plumbing, LED bulb making, drone operation, etc.",
        "max_income": 500000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Self-Help Group Member", "Artisan"],
        "eligible_categories": ["All"],
        "gender": "Female",
        "required_documents": ["SHG Membership Card", "Aadhaar Card", "Income Proof"],
        "deadline": "Ongoing",
        "apply_url": "https://nrlm.gov.in/",
        "category": "Skill Development",
        "popularity": 87,
        "guidance_steps": [
            "Join or be an active member of a local SHG.",
            "Express interest in skill training to the SHG leader.",
            "Select a trade for specialized vocational training.",
            "Access micro-credit through the SHG for enterprise setup."
        ]
    },
    {
        "id": "pm_surya_ghar",
        "name": "PM Surya Ghar: Muft Bijli Yojana",
        "icon": "☀️",
        "description": "Providing free electricity to households by offering subsidies for rooftop solar installation.",
        "benefits": "Free electricity up to 300 units per month and subsidy up to ₹78,000.",
        "max_income": 999999,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "land_owned_required": True,
        "required_documents": ["Electricity Bill", "Property Documents", "Aadhaar Card"],
        "deadline": "Open",
        "apply_url": "https://pmsuryaghar.gov.in/",
        "category": "Welfare",
        "popularity": 96,
        "guidance_steps": [
            "Register on the PM Surya Ghar portal.",
            "Submit your consumer number and electricity board details.",
            "Apply for Rooftop Solar installation.",
            "Wait for feasibility approval and install solar panels via registered vendors."
        ]
    },
    {
        "id": "pm_jan_dhan",
        "name": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
        "icon": "🏦",
        "description": "National Mission for Financial Inclusion to ensure access to financial services.",
        "benefits": "Zero-balance savings account, accidental insurance of ₹2 Lakh, and overdraft facility.",
        "max_income": 9999999,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "required_documents": ["Aadhaar Card", "Voter ID Or PAN"],
        "deadline": "Open",
        "apply_url": "https://pmjdy.gov.in/",
        "category": "Finance",
        "popularity": 99,
        "guidance_steps": [
            "Visit any bank branch or Bank Mitras (Business Correspondents).",
            "Fill out the account opening form.",
            "Provide e-KYC via Aadhaar.",
            "Collect your RuPay Debit Card and passbook."
        ]
    },
    {
        "id": "pm_jeevan_jyoti",
        "name": "PM Jeevan Jyoti Bima Yojana (PMJJBY)",
        "icon": "🛡️",
        "description": "One-year life insurance scheme renewable from year to year.",
        "benefits": "Life cover of ₹2 Lakh in case of death due to any reason.",
        "max_income": 5000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "min_age": 18,
        "max_age": 50,
        "required_documents": ["Savings Bank Account", "Aadhaar Card"],
        "deadline": "Ongoing",
        "apply_url": "https://jansuraksha.gov.in/",
        "category": "Finance",
        "popularity": 88
    },
    {
        "id": "pm_suraksha_bima",
        "name": "PM Suraksha Bima Yojana (PMSBY)",
        "icon": "🚑",
        "description": "Accidental insurance scheme for death or disability due to an accident.",
        "benefits": "₹2 Lakh for accidental death or total disability; ₹1 Lakh for partial disability.",
        "max_income": 5000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "min_age": 18,
        "max_age": 70,
        "required_documents": ["Savings Bank Account", "Aadhaar Card"],
        "deadline": "Ongoing",
        "apply_url": "https://jansuraksha.gov.in/",
        "category": "Finance",
        "popularity": 89
    },
    {
        "id": "pm_shri",
        "name": "PM SHRI Schools",
        "icon": "🏫",
        "description": "Centrally sponsored scheme for development of more than 14,500 schools across India.",
        "benefits": "High-quality education in a NEP 2020 compliant environment, advanced labs, and holistic development.",
        "max_income": 9999999,
        "eligible_states": ["All"],
        "eligible_occupations": ["Student"],
        "eligible_categories": ["All"],
        "required_documents": ["School Admission Proof"],
        "deadline": "Admission Based",
        "apply_url": "https://pmshrischools.education.gov.in/",
        "category": "Education",
        "popularity": 79
    },
    {
        "id": "naps_apprenticeship",
        "name": "National Apprenticeship Promotion Scheme (NAPS)",
        "icon": "🔧",
        "description": "Promoting apprenticeship training and incentivizing employers who engage apprentices.",
        "benefits": "Stipend support and skill certification by the government.",
        "max_income": 2000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Student", "Unemployed", "Trainee"],
        "eligible_categories": ["All"],
        "min_age": 14,
        "required_documents": ["Education Qualification Certificates", "Aadhaar"],
        "deadline": "Open",
        "apply_url": "https://www.apprenticeshipindia.gov.in/",
        "category": "Employment",
        "popularity": 81
    },
    {
        "id": "antyodaya_anna",
        "name": "Antyodaya Anna Yojana (AAY)",
        "icon": "🌾",
        "description": "Reaching out to the poorest of the poor by providing highly subsidized food grains.",
        "benefits": "35 kg of food grains at ₹2 per kg (wheat) and ₹3 per kg (rice) per family.",
        "max_income": 100000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Manual Labor", "Daily Wager", "Artisan"],
        "eligible_categories": ["General (BPL)"],
        "required_documents": ["AAY Ration Card", "Income Certificate"],
        "deadline": "Rolling",
        "apply_url": "https://nfsa.gov.in/",
        "category": "Food Security",
        "popularity": 92
    },
    {
        "id": "pm_pvtg_mission",
        "name": "PM PVTG Development Mission",
        "icon": "🏹",
        "description": "Holistic development of Particular Vulnerable Tribal Groups (PVTGs).",
        "benefits": "Saturation of basic facilities like housing, clean water, road connectivity, and health.",
        "max_income": 200000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["ST (PVTG)"],
        "required_documents": ["Caste Certificate", "Aadhaar Card"],
        "deadline": "Ongoing",
        "apply_url": "https://tribal.nic.in/",
        "category": "Social Welfare",
        "popularity": 73
    },
    {
        "id": "agnipath_scheme",
        "name": "Agnipath Scheme (Agniveer)",
        "icon": "🎖️",
        "description": "Short-term service in the Indian Armed Forces (Army, Navy, Air Force).",
        "benefits": "Seva Nidhi package of ₹11.7 Lakhs after 4 years, skill certificates, and training.",
        "max_income": 9999999,
        "eligible_states": ["All"],
        "eligible_occupations": ["Unemployed", "Student"],
        "eligible_categories": ["All"],
        "min_age": 17,
        "max_age": 21,
        "required_documents": ["Educational Certificates", "Physical Fitness Certificate", "Aadhaar"],
        "deadline": "Batch Wise",
        "apply_url": "https://joinindianarmy.nic.in/agnipath.htm",
        "category": "Employment",
        "popularity": 95,
        "guidance_steps": [
            "Register on the official defense recruitment portals.",
            "Apply for the specific Agniveer notification.",
            "Attend the physical and medical tests.",
            "Clear the common entrance exam (CEE)."
        ]
    },
    {
        "id": "mahila_samman_savings",
        "name": "Mahila Samman Savings Certificate",
        "icon": "💳",
        "description": "Small savings scheme specifically for women and girl children.",
        "benefits": "Fixed interest rate of 7.5% per annum and tax benefits.",
        "max_income": 5000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["All"],
        "eligible_categories": ["All"],
        "gender": "Female",
        "required_documents": ["Aadhaar", "PAN Card", "Cheque/Cash for Deposit"],
        "deadline": "March 2025",
        "apply_url": "https://www.indiapost.gov.in/",
        "category": "Finance",
        "popularity": 83
    },
    {
        "id": "pm_ebus_sewa",
        "name": "PM eBus Sewa",
        "icon": "🚌",
        "description": "Improving urban transport by deploying 10,000 electric buses in 169 cities.",
        "benefits": "Modern, clean transport and extensive employment in the Green Energy sector.",
        "max_income": 500000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Driver", "Technician", "Urban Worker"],
        "eligible_categories": ["All"],
        "required_documents": ["Driving License", "Skill Certificate"],
        "deadline": "Project Based",
        "apply_url": "https://mohua.gov.in/",
        "category": "Infrastructure",
        "popularity": 70
    },
    {
        "id": "pm_fme_scheme",
        "name": "PM Formalisation of Micro Food Processing Enterprises (PMFME)",
        "icon": "🥫",
        "description": "Providing technical, financial and business support for micro food processing units.",
        "benefits": "Credit-linked subsidy up to 35% of project cost (max ₹10 Lakhs).",
        "max_income": 2000000,
        "eligible_states": ["All"],
        "eligible_occupations": ["Business Owner", "Entrepreneur", "Farmer Group"],
        "eligible_categories": ["All"],
        "required_documents": ["Project Report", "Registration Certificates", "Aadhaar"],
        "deadline": "Open",
        "apply_url": "https://pmfme.mofpi.gov.in/",
        "category": "Finance",
        "popularity": 76,
        "guidance_steps": [
            "Prepare a detailed project report for your food processing unit.",
            "Apply on the PMFME portal.",
            "Engage with the District Resource Person (DRP) for assistance.",
            "Secure loan approval from a participating bank for the subsidy."
        ]
    }
]

def seed_db():
    db = SessionLocal()
    try:
        # Create tables first
        Base.metadata.create_all(bind=engine)

        # Clear and Re-seed to ensure schema updates are applied
        db.query(Scheme).delete()
        print("Cleared existing schemes for fresh seed...")

        for s_data in SCHEMES_LIST:
            scheme = Scheme(**s_data)
            db.add(scheme)
        
        db.commit()
        print(f"Successfully seeded {len(SCHEMES_LIST)} schemes into the database.")
    except Exception as e:
        print(f"Error seeding database: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_db()

if __name__ == "__main__":
    seed_db()
